namespace LangChain.Databases;

/// <summary>
/// Vector collection(table).
/// One database can have multiple collections.
/// One collection can have multiple vectors.
/// </summary>
public class VectorCollection
{
    public const string DefaultName = "langchain";

    /// <summary>
    /// Identifier of collection generated by Vector Database.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Collection name provided by client.
    /// </summary>
    public string Name { get; set; } = string.Empty;
}